### ISSUE TITLE
OSX - NodeJS v5.5.0 - mern 0.0.1 - crash

### ISSUE THREAD

**Issue by otobrglez** [Hashnode/mern-starter#14]
Hey guys!

I'm tried to install and use `mern` (0.0.1 installed as global) on my OSX (10.10.5) with NodeJS v5.5.0. After successfully creating new project with `merv <project_name>`, I did `npm install`. And the when i try to `npm start` I get following crash.

```
npm start        

> mern-starter@1.0.0 start /Users/otobrglez/Projects/dodo
> cross-env NODE_ENV=development node index.js

MERN is running on port: 8000! Build something amazing!

/Users/otobrglez/Projects/dodo/node_modules/mongodb/lib/server.js:236
        process.nextTick(function() { throw err; })
                                      ^
Error: connect ECONNREFUSED 127.0.0.1:27017
    at Object.exports._errnoException (util.js:856:11)
    at exports._exceptionWithHostPort (util.js:879:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1062:14)

npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/Cellar/node/5.5.0/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v5.5.0
npm ERR! npm  v3.5.3
npm ERR! code ELIFECYCLE
npm ERR! mern-starter@1.0.0 start: `cross-env NODE_ENV=development node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mern-starter@1.0.0 start script 'cross-env NODE_ENV=development node index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mern-starter package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env NODE_ENV=development node index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mern-starter
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls mern-starter
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/otobrglez/Projects/dodo/npm-debug.log
```

This is ziped NPM debug log: [npm-debug.log.zip](https://github.com/Hashnode/mern-starter/files/136030/npm-debug.log.zip)

Any ideas?

Cheers!

**Comment by mayankchd** [comment]
Hi.. You need to have MongoDB up and running in order to proceed.

**Comment by otobrglez** [comment]
It works. Perfect! :+1: 

Could the instructions be something like this?

```
> npm install -g mern-cli
> mern <YourAppName>
> cd YourAppName
> npm install
> npm start
```
