### ISSUE TITLE
Error: Cannot find module 'slug'

### ISSUE THREAD

**Issue by ahmadsafar** [Hashnode/mern-starter#145]
i run it in Windows 10, but got this error. what i'm missing?
```
$ npm start

> mern-starter@1.0.0 start D:\meteor\mern\halojasa
> cross-env NODE_ENV=development node_modules/.bin/nodemon index.js

[nodemon] 1.9.2
[nodemon] reading config D:\meteor\mern\halojasa\nodemon.json
[nodemon] to restart at any time, enter `rs`
[nodemon] ignoring: D:\meteor\mern\halojasa\.git/**/* .nyc_output .sass-cache bower_components coverage D:\meteor\mern\halojasa\node_modules/**/* D:\meteor\mern\halojasa\.git/**/* node_modules/**/node_modules
[nodemon] watching: D:\meteor\mern\halojasa\server/**/*
[nodemon] watching extensions: js,json
[nodemon] starting `node index.js`
[nodemon] child pid: 7312
[nodemon] watching 9 files
module.js:442
    throw err;
    ^

Error: Cannot find module 'slug'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (post.controller.js:3:1)
    at Module._compile (module.js:541:32)
    at loader (D:\meteor\mern\halojasa\node_modules\babel-register\lib\node.js:158:5)
    at Object.require.extensions.(anonymous function) [as .js] (D:\meteor\mern\halojasa\node_modules\babel-register\lib\node.js:168:7)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (post.routes.js:2:1)
    at Module._compile (module.js:541:32)
    at loader (D:\meteor\mern\halojasa\node_modules\babel-register\lib\node.js:158:5)
    at Object.require.extensions.(anonymous function) [as .js] (D:\meteor\mern\halojasa\node_modules\babel-register\lib\node.js:168:7)
[nodemon] app crashed - waiting for file changes before starting..
```

**Comment by joernroeder** [comment]
you're missing the `slug` module which will be required [here](https://github.com/Hashnode/mern-starter/blob/master/server/controllers/post.controller.js#L3). Did you run `npm install` before starting the server?

**Comment by ahmadsafar** [comment]
After do `npm install`. i got this:

```
> buffertools@2.1.4 install D:\meteor\mern\halojasa\node_modules\buffertools
> node-gyp rebuild


D:\meteor\mern\halojasa\node_modules\buffertools>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targets(366,5): warni
ng MSB8003: Could not find WindowsSDKDir variable from the registry.  TargetFrameworkVersion or
 PlatformToolset may be set to an invalid version number. [D:\meteor\mern\halojasa\node_modules
\buffertools\build\buffertools.vcxproj]
TRACKER : error TRK0005: Failed to locate: "CL.exe". The system cannot find the file specified.
 [D:\meteor\mern\halojasa\node_modules\buffertools\build\buffertools.vcxproj]


gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\meteor\mern\halojasa\node_modules\buffertools
gyp ERR! node -v v6.2.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
npm WARN install:buffertools@2.1.4 buffertools@2.1.4 install: `node-gyp rebuild`
npm WARN install:buffertools@2.1.4 Exit status 1

> nodejieba@1.4.11 install D:\meteor\mern\halojasa\node_modules\nodejieba
> node-gyp rebuild


D:\meteor\mern\halojasa\node_modules\nodejieba>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targets(366,5): warni
ng MSB8003: Could not find WindowsSDKDir variable from the registry.  TargetFrameworkVersion or
 PlatformToolset may be set to an invalid version number. [D:\meteor\mern\halojasa\node_modules
\nodejieba\build\nodejieba.vcxproj]
TRACKER : error TRK0005: Failed to locate: "CL.exe". The system cannot find the file specified.
 [D:\meteor\mern\halojasa\node_modules\nodejieba\build\nodejieba.vcxproj]


gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\meteor\mern\halojasa\node_modules\nodejieba
gyp ERR! node -v v6.2.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
npm WARN install:nodejieba@1.4.11 nodejieba@1.4.11 install: `node-gyp rebuild`
npm WARN install:nodejieba@1.4.11 Exit status 1

> unicode@0.6.1 postinstall D:\meteor\mern\halojasa\node_modules\unicode
> node install.js

try to read file /usr/share/unicode/UnicodeData.txt …
Warning: using slow naiv Buffer.indexOf function!
`npm install buffertools` to speed things up.
/usr/share/unicode/UnicodeData.txt not found.
try to read file /usr/share/unicode-data/UnicodeData.txt …
/usr/share/unicode-data/UnicodeData.txt not found.
try to read file UnicodeData.txt …
UnicodeData.txt not found.
try to download …
GET unicode.org:80/Public/UNIDATA/UnicodeData.txt
fetching …
D:\meteor\mern\halojasa\node_modules\bufferjs\indexOf.js:16
        if (haystack.get(i+j) !== needle.get(j)) {
                     ^

TypeError: haystack.get is not a function
    at indexOf (D:\meteor\mern\halojasa\node_modules\bufferjs\indexOf.js:16:22)
    at Buffer.exports.indexOf (D:\meteor\mern\halojasa\node_modules\bufferstream\lib\fn.js:16:14)
    at BufferStream.split (D:\meteor\mern\halojasa\node_modules\bufferstream\lib\buffer-stream.js:30:24)
    at BufferStream.write (D:\meteor\mern\halojasa\node_modules\bufferstream\lib\buffer-stream.js:210:17)
    at BufferStream.write (D:\meteor\mern\halojasa\node_modules\bufferstream\lib\buffer-stream.js:3:61)
    at IncomingMessage.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at IncomingMessage.emit (events.js:188:7)
    at IncomingMessage.Readable.read (_stream_readable.js:387:10)
    at flow (_stream_readable.js:764:26)
mern-starter@1.0.0 D:\meteor\mern\halojasa
`-- limax@1.2.0  extraneous

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.12
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.2.0
npm ERR! npm  v3.8.9
npm ERR! code ELIFECYCLE

npm ERR! unicode@0.6.1 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the unicode@0.6.1 postinstall script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the unicode package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs unicode
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls unicode
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\meteor\mern\halojasa\npm-debug.log
```

**Comment by joernroeder** [comment]
you're getting the `haystack.get is not a function error` which ist described here https://github.com/coolaj86/node-bufferjs/issues/13  
Change your node version (https://github.com/coreybutler/nvm-windows) and try to run `npm install` again.

**Comment by ahmadsafar** [comment]
okay fixed, thanks!
