### ISSUE TITLE
docker run issues

### ISSUE THREAD

**Issue by hrwebasst** [Hashnode/mern-starter#172]
Initially was getting complaints about rimraf not being installed. I installed that with npm but now `npm run bs` gives:

```bash
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'bs' ]
2 info using npm@3.9.5
3 info using node@v6.2.2
4 verbose run-script [ 'prebs', 'bs', 'postbs' ]
5 info lifecycle mern-starter@2.0.0~prebs: mern-starter@2.0.0
6 silly lifecycle mern-starter@2.0.0~prebs: no script for prebs, continuing
7 info lifecycle mern-starter@2.0.0~bs: mern-starter@2.0.0
8 verbose lifecycle mern-starter@2.0.0~bs: unsafe-perm in lifecycle true
9 verbose lifecycle mern-starter@2.0.0~bs: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/usr/src/app/node_modules/.bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
10 verbose lifecycle mern-starter@2.0.0~bs: CWD: /usr/src/app
11 silly lifecycle mern-starter@2.0.0~bs: Args: [ '-c',
11 silly lifecycle   'npm run clean && npm run build && npm run build:server && npm run start:prod' ]
12 silly lifecycle mern-starter@2.0.0~bs: Returned: code: 1  signal: null
13 info lifecycle mern-starter@2.0.0~bs: Failed to exec bs script
14 verbose stack Error: mern-starter@2.0.0 bs: `npm run clean && npm run build && npm run build:server && npm run start:prod`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:245:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:852:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid mern-starter@2.0.0
16 verbose cwd /usr/src/app
17 error Linux 4.4.0-24-generic
18 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "bs"
19 error node v6.2.2
20 error npm  v3.9.5
21 error code ELIFECYCLE
22 error mern-starter@2.0.0 bs: `npm run clean && npm run build && npm run build:server && npm run start:prod`
22 error Exit status 1
23 error Failed at the mern-starter@2.0.0 bs script 'npm run clean && npm run build && npm run build:server && npm run start:prod'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the mern-starter package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     npm run clean && npm run build && npm run build:server && npm run start:prod
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs mern-starter
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls mern-starter
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by hrwebasst** [comment]
This is the result of the development run docker with npm start:
```bash
root@349c568ebf41:/usr/src/app# npm start
npm info it worked if it ends with ok
npm info using npm@3.9.5
npm info using node@v6.2.2
npm info lifecycle mern-starter@2.0.0~prestart: mern-starter@2.0.0
npm info lifecycle mern-starter@2.0.0~start: mern-starter@2.0.0

> mern-starter@2.0.0 start /usr/src/app
> cross-env BABEL_DISABLE_CACHE=1 NODE_ENV=development nodemon index.js

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn nodemon ENOENT
    at exports._errnoException (util.js:1007:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:577:11)
    at run (node.js:348:7)
    at startup (node.js:140:9)
    at node.js:463:3

npm info lifecycle mern-starter@2.0.0~start: Failed to exec start script
npm ERR! Linux 4.4.0-24-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.2.2
npm ERR! npm  v3.9.5
npm ERR! code ELIFECYCLE
npm ERR! mern-starter@2.0.0 start: `cross-env BABEL_DISABLE_CACHE=1 NODE_ENV=development nodemon index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mern-starter@2.0.0 start script 'cross-env BABEL_DISABLE_CACHE=1 NODE_ENV=development nodemon index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mern-starter package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env BABEL_DISABLE_CACHE=1 NODE_ENV=development nodemon index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mern-starter
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls mern-starter
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/src/app/npm-debug.log
root@349c568ebf41:/usr/src/app# cat npm-debug.log 
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@3.9.5
3 info using node@v6.2.2
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle mern-starter@2.0.0~prestart: mern-starter@2.0.0
6 silly lifecycle mern-starter@2.0.0~prestart: no script for prestart, continuing
7 info lifecycle mern-starter@2.0.0~start: mern-starter@2.0.0
8 verbose lifecycle mern-starter@2.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle mern-starter@2.0.0~start: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/usr/src/app/node_modules/.bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
10 verbose lifecycle mern-starter@2.0.0~start: CWD: /usr/src/app
11 silly lifecycle mern-starter@2.0.0~start: Args: [ '-c',
11 silly lifecycle   'cross-env BABEL_DISABLE_CACHE=1 NODE_ENV=development nodemon index.js' ]
12 silly lifecycle mern-starter@2.0.0~start: Returned: code: 1  signal: null
13 info lifecycle mern-starter@2.0.0~start: Failed to exec start script
14 verbose stack Error: mern-starter@2.0.0 start: `cross-env BABEL_DISABLE_CACHE=1 NODE_ENV=development nodemon index.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:245:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:852:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid mern-starter@2.0.0
16 verbose cwd /usr/src/app
17 error Linux 4.4.0-24-generic
18 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
19 error node v6.2.2
20 error npm  v3.9.5
21 error code ELIFECYCLE
22 error mern-starter@2.0.0 start: `cross-env BABEL_DISABLE_CACHE=1 NODE_ENV=development nodemon index.js`
22 error Exit status 1
23 error Failed at the mern-starter@2.0.0 start script 'cross-env BABEL_DISABLE_CACHE=1 NODE_ENV=development nodemon index.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the mern-starter package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     cross-env BABEL_DISABLE_CACHE=1 NODE_ENV=development nodemon index.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs mern-starter
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls mern-starter
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by kandros** [comment]
The errors you facing looks like the port is occupied by a process already
what command as you using?

docker-compose actually runs the application already

```
docker-compose build
docker-compose up
```
listening on http://DOCKER_IP:80

**Comment by hrwebasst** [comment]
@kandros As you can see I was in the container when I ran the npm start command. I started the container by hand after the `docker-compose -f docker-compose-development.yml up` command output the same error. 

repro steps are easy run `docker-compose -f docker-compose-development.yml up` and you will see web_1 have that `event.js:160 throw er; // Unhandled 'error' event` happen.

It isn't possible that something was occupying the IP as I started the docker with `sh` command to output those. Also if I was already running a docker on port 80 and tried to allocate it the error would be with starting the container.

Hope this helps.

**Comment by kandros** [comment]
Il test and report when possibile, thanks for the logs
