### ISSUE TITLE
npm install got error on vagrant

### ISSUE THREAD

**Issue by khietvovan** [Hashnode/mern-starter#185]
NPM version: 3.10.2
NODE version: v4.4.0
I got this error when run npm install:
```
npm ERR! Linux 3.13.0-85-generic
npm ERR! argv "/home/vagrant/.nvm/versions/node/v4.4.0/bin/node" "/home/vagrant/.nvm/versions/node/v4.4.0/bin/npm" "install"
npm ERR! node v4.4.0
npm ERR! npm  v3.10.2
npm ERR! path /vagrant/mern-starter/node_modules/nyc/node_modules/foreground-child/node_modules/which/bin/which
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod

npm ERR! enoent ENOENT: no such file or directory, chmod '/vagrant/mern-starter/node_modules/nyc/node_modules/foreground-child/node_modules/which/bin/which'
npm ERR! enoent ENOENT: no such file or directory, chmod '/vagrant/mern-starter/node_modules/nyc/node_modules/foreground-child/node_modules/which/bin/which'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /vagrant/mern-starter/npm-debug.log

```
then I try to run `npm start`
And get this
```
/vagrant/mern-starter/node_modules/babel-core/lib/transformation/file/index.js:591
      throw err;
      ^

Error: /vagrant/mern-starter/server/server.js: Cannot find module '../features'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/vagrant/mern-starter/node_modules/caniuse-api/dist/index.js:19:32)
    at Module._compile (module.js:409:26)
    at Module._extensions..js (module.js:416:10)
    at Object.require.extensions.(anonymous function) [as .js] (/vagrant/mern-starter/node_modules/babel-register/lib/node.js:166:7)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by somus** [comment]
Try running
```
npm cache clean
rm -rf node_modules
npm install
```

Let me know if this solves your problem.

**Comment by amoshydra** [comment]
I manage to get it to work for my Vagrant on Windows while running Git Bash with adminstrative right on this config
- Linux 3.13.0-65-generic
- node v4.4.7
- npm  v3.10.5

Then I try to reproduce this problem by cloning the repo into a new folder and do npm install
Then I got this error:
```
npm ERR! Linux 3.13.0-65-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.4.7
npm ERR! npm  v3.10.5
npm ERR! path /vagrant/node_modules/nyc/node_modules/test-exclude/node_modules/read-pkg-up/node_modules/read-pkg/node_modules/normalize-package-data/node_modules/semver/bin/semver
npm ERR! code ENOENT
npm ERR! errno^C -2
npm ERR! syscall chmod

npm ERR! enoent ENOENT: no such file or directory, chmod '/vagrant/node_modules/nyc/node_modules/test-exclude/node_modules/read-pkg-up/node_modules/read-pkg/node_modules/normalize-package-data/node_modules/semver/bin/semver'
npm ERR! enoent ENOENT: no such file or directory, chmod '/vagrant/node_modules/nyc/node_modules/test-exclude/node_modules/read-pkg-up/node_modules/read-pkg/node_modules/normalize-package-data/node_modules/semver/bin/semver'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent
```

So I try to do 
```
npm cache clean
rm -rf node_modules
npm install
```

and I got the exact same error that @khietvovan got

I have tried cleaning the cache and removing node_modules repeatedly. I got different error and eventually come back to `npm ERR! enoent ENOENT: no such file or directory, chmod '/vagrant/mern-starter/node_modules/nyc/node_modules/foreground-child/node_modules/which/bin/which'`

**Comment by amoshydra** [comment]
Could this be relevant?
https://github.com/Hashnode/mern-cli/issues/16

**Comment by somus** [comment]
@amoshydra Glad, you figured it out. @khietvovan Even after trying @amoshydra suggestion, you are getting the error, feel free to open it.

**Comment by khietvovan** [comment]
Thank you. I'm moving to use Mern in Docker. But I will try with Vagrant again.

**Comment by amrnegm** [comment]
I had a similar problem but the error was related to `syscall open` rather than `syscall chmod`. There is some problem with shared folder as stated above. I followed @amoshydra's steps above, without running `chmod`, and modules installed. Thanks @amoshydra!

Still the root cause of this issue is not known! Hope someone can find it.
