### ISSUE TITLE
content is not defined

### ISSUE THREAD

**Issue by colinshen** [Hashnode/mern-starter#192]
sometimes I get this error
```
/Users/shensi/codes/uhccjProject/uhccjMain/client/modules/App/App.js:16
var _App = content.locals;
           ^

ReferenceError: content is not defined
    at Object.<anonymous> (App.js:5:1)
    at Module._compile (module.js:409:26)
    at loader (/Users/shensi/codes/uhccjProject/uhccjMain/node_modules/babel-register/lib/node.js:158:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/shensi/codes/uhccjProject/uhccjMain/node_modules/babel-register/lib/node.js:168:7)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (routes.js:4:1)
    at Module._compile (module.js:409:26)
    at loader (/Users/shensi/codes/uhccjProject/uhccjMain/node_modules/babel-register/lib/node.js:158:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/shensi/codes/uhccjProject/uhccjMain/node_modules/babel-register/lib/node.js:168:7)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
```

**Comment by kieusonlam** [comment]
Hi colinshen,

I'm pretty new to MERN. I got same problem too. How did you get though this?

**Comment by olya-pysarenko** [comment]
Hi colinshen!
I've got the same error and have no idea how to solve it. Could you help me with this issue?

var _App = content.locals;
           ^
ReferenceError: content is not defined
    at Object.<anonymous> (/Users/olya/Documents/projects/penguin-krachuk/client/modules/App/App.js:5:1)
    at Module._compile (module.js:556:32)
    at loader (/Users/olya/Documents/projects/penguin-krachuk/node_modules/babel-register/lib/node.js:146:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/olya/Documents/projects/penguin-krachuk/node_modules/babel-register/lib/node.js:156:7)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/olya/Documents/projects/penguin-krachuk/client/routes.js:4:1)
    at Module._compile (module.js:556:32)
    at loader (/Users/olya/Documents/projects/penguin-krachuk/node_modules/babel-register/lib/node.js:146:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/olya/Documents/projects/penguin-krachuk/node_modules/babel-register/lib/node.js:156:7)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by kieusonlam** [comment]
@olya-pysarenko You can check out this https://github.com/Hashnode/mern-starter/issues/224

**Comment by olya-pysarenko** [comment]
@kieusonlam , thanks, it works for me!

**Comment by sham3k** [comment]
Downgrading to Webpack ^1.13.3 seems to solve it. Wierd bug, though.
