### ISSUE TITLE
__webpack_require__ is not defined while using css-modules 'composes'

### ISSUE THREAD

**Issue by osenvosem** [Hashnode/mern-starter#193]
When I use css modules `composes` feature I get en error:
```
/Volumes/Data/development/dev/one/client/modules/Post/components/PostListItem/PostListItem.js:16
  "single-post": "PostListItem__single-post__3B15Q " + __webpack_require__(0).locals["test-style"] + "",
                                                       ^

ReferenceError: __webpack_require__ is not defined
    at Object.<anonymous> (PostListItem.js:6:1)
    at Module._compile (module.js:541:32)
    at loader (/Volumes/Data/development/dev/one/node_modules/babel-register/lib/node.js:158:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Volumes/Data/development/dev/one/node_modules/babel-register/lib/node.js:168:7)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (PostList.js:4:1)
    at Module._compile (module.js:541:32)
    at loader (/Volumes/Data/development/dev/one/node_modules/babel-register/lib/node.js:158:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Volumes/Data/development/dev/one/node_modules/babel-register/lib/node.js:168:7)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by isaacjohnsononline** [comment]
Having the same issue

**Comment by somus** [comment]
I just checked, and composing classes work. Here is how I did it.

For within the same file
```
.someClass  {
}
.otherClass {
    composes: someClass;
}
```

From a different file
```
.otherClass {
    composes: someClass from "../../OtherFile/OtherFile.css"; // relative path to that file
}
```

Reopen the issue if it still persists.

**Comment by adrianha** [comment]
hi @somus , i still got the same issues..
i cant composes using class from another file..

**Comment by varya** [comment]
The same issue for me.

**Comment by yp2** [comment]
Same here

**Comment by zdenekhynek** [comment]
@yp2 @varya @adrianha Have you ever found a solution?

**Comment by adrianha** [comment]
hi @zdenekhynek , Still got no luck about this issue.

**Comment by artemverbo** [comment]
+1 still happening, tried loading @value variables from a different file. It did work when I've just added that without restarting the dev server, but a fresh restart is crashing.
