### ISSUE TITLE
ES6 spread operator

### ISSUE THREAD

**Issue by maciejmyslinski** [Hashnode/mern-starter#204]
I just installed mern-starter without any modifications.
When I run `npm start` I get an error:
```bash
SyntaxError: mern-starter/client/modules/Intl/IntlReducer.js: Unexpected token (9:2)
   7 |   locale: initLocale,
   8 |   enabledLanguages,
>  9 |   ...(localizationData[initLocale] || {}),
     |   ^
  10 | };
  11 |
  12 | const IntlReducer = (state = initialState, action) => {
    at Parser.pp.raise (mern-starter/node_modules/babylon/lib/parser/location.js:22:13)
    at Parser.pp.unexpected (mern-starter/node_modules/babylon/lib/parser/util.js:89:8)
    at Parser.pp.parseIdentifier (mern-starter[nodemon] app crashed - waiting for file changes before starting...
```

It seems like it do not like es6 spread operator. Strange, isn't it?
Where I got wrong?

**Comment by maciejmyslinski** [comment]
Ok, nvm. I did something wrong when upgrading.
