### ISSUE TITLE
Error while npm Start

### ISSUE THREAD

**Issue by designviacode** [Hashnode/mern-starter#212]
Hi everyone, I've tried to setup mern-starter using NVM, 
tried using :
  [ + ]  Node v6.3.1 and npm 3.10.3 (Latest) 
  [ + ]  Node v4.4.7 and npm 2.15.8 (LTS)
on Ubuntu 16.04.1 (LTS).

I did a clean install by cloning the repo. On running "npm start" I get the following error.
Any thoughts or workarounds would be appreciated.

```
module.js:327
    throw err;
    ^

Error: Cannot find module '/media/manpreet/Media'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3
/media/manpreet/Media and Files/work projects/mern-starter/node_modules/babel-core/lib/transformation/file/index.js:591
      throw err;
      ^

Error: /media/manpreet/Media and Files/work projects/mern-starter/client/modules/App/App.js: Command failed: node /media/manpreet/Media and Files/work projects/mern-starter/node_modules/webpack/bin/webpack.js /media/manpreet/Media and Files/work projects/mern-starter/client/modules/App/App.css /tmp/.webpack.res.1469537186753_457444.js --config ./webpack.config.babel.js --bail
module.js:327
    throw err;
    ^

Error: Cannot find module '/media/manpreet/Media'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3

    at checkExecSyncError (child_process.js:464:13)
    at execSync (child_process.js:504:13)
    at exports.default (/media/manpreet/Media and Files/work projects/mern-starter/node_modules/babel-plugin-webpack-loaders/lib/runWebPackSync.js:39:51)
    at PluginPass.CallExpression (/media/manpreet/Media and Files/work projects/mern-starter/node_modules/babel-plugin-webpack-loaders/lib/plugin.js:101:60)
    at newFn (/media/manpreet/Media and Files/work projects/mern-starter/node_modules/babel-core/node_modules/babel-traverse/lib/visitors.js:301:19)
    at NodePath._call (/media/manpreet/Media and Files/work projects/mern-starter/node_modules/babel-core/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/media/manpreet/Media and Files/work projects/mern-starter/node_modules/babel-core/node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (/media/manpreet/Media and Files/work projects/mern-starter/node_modules/babel-core/node_modules/babel-traverse/lib/path/context.js:106:12)
    at TraversalContext.visitQueue (/media/manpreet/Media and Files/work projects/mern-starter/node_modules/babel-core/node_modules/babel-traverse/lib/context.js:167:16)
    at TraversalContext.visitSingle (/media/manpreet/Media and Files/work projects/mern-starter/node_modules/babel-core/node_modules/babel-traverse/lib/context.js:118:19)
    at TraversalContext.visit (/media/manpreet/Media and Files/work projects/mern-starter/node_modules/babel-core/node_modules/babel-traverse/lib/context.js:211:19)
    at Function.traverse.node (/media/manpreet/Media and Files/work projects/mern-starter/node_modules/babel-core/node_modules/babel-traverse/lib/index.js:161:17)
    at NodePath.visit (/media/manpreet/Media and Files/work projects/mern-starter/node_modules/babel-core/node_modules/babel-traverse/lib/path/context.js:116:19)
    at TraversalContext.visitQueue (/media/manpreet/Media and Files/work projects/mern-starter/node_modules/babel-core/node_modules/babel-traverse/lib/context.js:167:16)
    at TraversalContext.visitMultiple (/media/manpreet/Media and Files/work projects/mern-starter/node_modules/babel-core/node_modules/babel-traverse/lib/context.js:113:17)
    at TraversalContext.visit (/media/manpreet/Media and Files/work projects/mern-starter/node_modules/babel-core/node_modules/babel-traverse/lib/context.js:209:19)
    at Function.traverse.node (/media/manpreet/Media and Files/work projects/mern-starter/node_modules/babel-core/node_modules/babel-traverse/lib/index.js:161:17)
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by sathyalog** [comment]
i am also facing the same issue. Can any one help to resolve this??

**Comment by Werbelow** [comment]
+1

**Comment by Werbelow** [comment]
Figured it out, it was due to my parent folder having a space in it's name. Once I removed the space, it worked. 

Hopefully, this helps out.

**Comment by designviacode** [comment]
Thanks @Werbelow.. This does seem to fix it.. Thanks a lot.. 😉 😊

**Comment by kunzhang1110** [comment]
I twisted the runWebPackSync.js file a bit by allowing spaces on windows path, and it worked fine.

	var pathString = [webPackPath, path, outPath, configPath].map(x => {return '\"' + x + '\"'});	//allow white spaces in path for windows
	
	var webPackStdOut = (0, _child_process.execSync)(['node', // for windows support
  pathString[0], pathString[1], pathString[2], '--config', pathString[3], '--bail'].join(' '));
