### ISSUE TITLE
Failed to install

### ISSUE THREAD

**Issue by custa1200** [Hashnode/mern-starter#215]
Just tried to follow the instructions on the mean.io home page and got the following at the end of my log when it started to fail
```
443916 info install mern-starter@2.0.0
443917 info postinstall mern-starter@2.0.0
443918 info prepublish mern-starter@2.0.0
443919 verbose validateInstall loading /Users/custa/Projects/mern/mern-starter/package.json for validation
443920 verbose stack Error: The package webpack@2.1.0-beta.20 does not satisfy its siblings' peerDependencies requirements!
443920 verbose stack     at /usr/local/lib/node_modules/npm/lib/install.js:125:32
443920 verbose stack     at /usr/local/lib/node_modules/npm/lib/install.js:268:7
443920 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-installed/read-installed.js:142:5
443920 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-installed/read-installed.js:263:14
443920 verbose stack     at cb (/usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
443920 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-installed/read-installed.js:263:14
443920 verbose stack     at cb (/usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
443920 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-installed/read-installed.js:263:14
443920 verbose stack     at cb (/usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
443920 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-installed/read-installed.js:263:14
443921 verbose cwd /Users/custa/Projects/mern/mern-starter
443922 error Darwin 16.0.0
443923 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
443924 error node v4.4.4
443925 error npm  v2.15.1
443926 error code EPEERINVALID
443927 error peerinvalid The package webpack@2.1.0-beta.20 does not satisfy its siblings' peerDependencies requirements!
443927 error peerinvalid Peer babel-loader@6.2.4 wants webpack@1 || ^2.1.0-beta
443927 error peerinvalid Peer extract-text-webpack-plugin@1.0.1 wants webpack@^1.9.11
443927 error peerinvalid Peer chunk-manifest-webpack-plugin@0.1.0 wants webpack@^1.4.0-beta6
443927 error peerinvalid Peer webpack-dev-middleware@1.6.1 wants webpack@1 || ^2.1.0-beta
443927 error peerinvalid Peer babel-plugin-webpack-loaders@0.7.0 wants webpack@>=1.12.9 <3.0.0
443927 error peerinvalid Peer webpack-dev-server@2.1.0-beta.0 wants webpack@^2.1.0-beta
443928 verbose exit [ 1, true ]
```

**Comment by custa1200** [comment]
Should say I am running 10.12 pb2. After a bit of reading it looks like it's likely this won't work on this system as Mongo isn't supported yet.

**Comment by mmintel** [comment]
exact same error here on fresh install

**Comment by hugofqueiros** [comment]
I'm having the same issue, but I think it's because you need to use npm version 3.

**Comment by mmintel** [comment]
thanks @hugofqueiros , that solved it for me

**Comment by somus** [comment]
As @hugofqueiros said mern requires npm 3 because peer dependencies of some of the packages used by mern. I'm closing the issue for now. @custa1200 If you face the issue after that, feel free to open it.
