### ISSUE TITLE
What is the right way to create a module and add new route?

### ISSUE THREAD

**Issue by kieusonlam** [Hashnode/mern-starter#224]
Hi everone,

I just know the basic of React Redux, and i need your help :)

I found MERN and I using it to make an small app to learn. I clone mern-start and use mern-cli to create a Test module. I just simple render a Hello World text.

	class Test extends Component {
	  render() {
	    return (
	      <div>Hello World</div>
	    );
	  }
	}

then i go to /client/route.js and add a new route under post route.

	<Route
	      path="/test"
	      getComponent={(nextState, cb) => {
	        require.ensure([], require => {
	          cb(null, require('./modules/Test/Test').default);
	        });
	      }}
	    />

restart from console and i got this error

	C:\Users\kieus\Desktop\MERN\client\modules\Auth\Auth.js:17
	var _Auth = content.locals;
	            ^
	
	ReferenceError: content is not defined
	    at Object.<anonymous> (Auth.js:6:1)
	    at Module._compile (module.js:541:32)
	    at loader (C:\Users\kieus\Desktop\MERN\node_modules\babel-register\lib\node.js:148:5)
	    at Object.require.extensions.(anonymous function) [as .js] (C:\Users\kieus\Desktop\MERN\node_modules\babel-register\lib\node.js:158:7)
	    at Module.load (module.js:458:32)
	    at tryModuleLoad (module.js:417:12)
	    at Function.Module._load (module.js:409:3)
	    at Module.require (module.js:468:17)
	    at require (internal/module.js:20:19)
	    at Object.<anonymous> (routes.js:21:3)
	    at Module._compile (module.js:541:32)
	    at loader (C:\Users\kieus\Desktop\MERN\node_modules\babel-register\lib\node.js:148:5)
	    at Object.require.extensions.(anonymous function) [as .js] (C:\Users\kieus\Desktop\MERN\node_modules\babel-register\lib\node.js:158:7)
	    at Module.load (module.js:458:32)
	    at tryModuleLoad (module.js:417:12)
	    at Function.Module._load (module.js:409:3)
	 [nodemon] app crashed - waiting for file changes before starting...

am i missing something? What i have to do to make it right :(

Also css background not working in development mode right?

Is there any tutorial about MERN for beginer like: create basic module, jwt authentication?

I know too many questions. Please help me Thanks.

**Comment by Morganjackson** [comment]
@kieusonlam Did you find a fix for this? I'm seeing the same thing after running ``mern init`` & ``merng module Editor`` using the latest mern-cli.

**Comment by Morganjackson** [comment]
Removing the usused style imports fixed this for me. ``import styles from './Editor.css';``

**Comment by kieusonlam** [comment]
Thanks @Morganjackson error gone away. :+1:

**Comment by alanhorizon** [comment]
wish I had found this issue before spending half a day debugging. I wonder what's ACTUALLY going on here. an empty styles import should not cause a cryptic "segmentation fault"-like error message like this.

**Comment by sham3k** [comment]
Downgrading to Webpack ^1.13.3 solved it. Strange bug, though.
