### ISSUE TITLE
Start Up Error - "TypeError: Cannot assign to read only property 'Intl' of [object global]"

### ISSUE THREAD

**Issue by cantuket** [Hashnode/mern-starter#231]
/Users/kylegermaine/apps/node/mern-test/Intl/setup.js:51
global.Intl = _intl2.default;
            ^
TypeError: Cannot assign to read only property 'Intl' of [object global]
    at Object.<anonymous> (/Users/kylegermaine/apps/node/mern-test/Intl/setup.js:19:1)
    at Module._compile (module.js:460:26)
    at loader (/Users/kylegermaine/apps/node/mern-test/node_modules/babel-register/lib/node.js:146:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/kylegermaine/apps/node/mern-test/node_modules/babel-register/lib/node.js:156:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/kylegermaine/apps/node/mern-test/client/modules/Intl/IntlReducer.js:1:1)
    at Module._compile (module.js:460:26)
    at loader (/Users/kylegermaine/apps/node/mern-test/node_modules/babel-register/lib/node.js:146:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/kylegermaine/apps/node/mern-test/node_modules/babel-register/lib/node.js:156:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)

This was my first time running the Quick Start. Any help would be greatly appreciated.  Do I need to update Babel?

Thanks,
Kyle

**Comment by somus** [comment]
I don't think the problem is related to babel. This code is related to `Intl` polyfilling. I was polyfilling even if `Intl` was present. Now, I've updated the code in b7c79f44db7db07495d208c045fe7f41cc8391fb. Try doing a fresh install now and let me know if the problem still persists?

**Comment by cantuket** [comment]
Awesome, thanks @somus. I'm up and running now!
