### ISSUE TITLE
Unhandled 'error' event

### ISSUE THREAD

**Issue by tpham045** [Hashnode/mern-starter#282]
Hello!

I am not familiar with Mongo, Node, and Express. Could you help please? Here is the error:

**Error in terminal:**
```
tpham045:~/workspace/portfolio (master) $ npm start

> mern-starter@2.0.0 start /home/ubuntu/workspace/portfolio
> cross-env BABEL_DISABLE_CACHE=1 NODE_ENV=development nodemon index.js

[nodemon] 1.11.0
[nodemon] reading config /home/ubuntu/workspace/portfolio/nodemon.json
[nodemon] to restart at any time, enter `rs`
[nodemon] ignoring: /home/ubuntu/workspace/portfolio/.git/**/* .nyc_output .sass-cache bower_components coverage /home/ubuntu/workspace/portfolio/node_modules/**/* /home/ubuntu/workspace/portfolio/.git/**/* node_modules/**/node_modules
[nodemon] watching: /home/ubuntu/workspace/portfolio/server/**/* /home/ubuntu/workspace/portfolio/Intl/**/*
[nodemon] watching extensions: js,json
[nodemon] starting `node index.js`
[nodemon] child pid: 6921
[nodemon] watching 14 files
MERN is running on port: 8080! Build something amazing!
webpack built 40146aa1e8b35c1087e1 in 61810ms
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: connection timeout
    at null.<anonymous> (/home/ubuntu/workspace/portfolio/node_modules/mongoose/lib/drivers/node-mongodb-native/connection.js:169:17)
    at emitTwo (events.js:87:13)
    at null.emit (events.js:172:7)
    at null.listener (/home/ubuntu/workspace/portfolio/node_modules/mongoose/node_modules/mongodb/lib/db.js:1795:14)
    at emitOne (events.js:77:13)
    at null.emit (events.js:169:7)
    at null.<anonymous> (/home/ubuntu/workspace/portfolio/node_modules/mongoose/node_modules/mongodb/lib/server.js:274:14)
    at emitOne (events.js:77:13)
    at null.emit (events.js:169:7)
    at null.<anonymous> (/home/ubuntu/workspace/portfolio/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:335:12)
    at emitOne (events.js:77:13)
    at null.emit (events.js:169:7)
    at null.<anonymous> (/home/ubuntu/workspace/portfolio/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/connection/pool.js:272:12)
    at null.g (events.js:260:16)
    at emitTwo (events.js:87:13)
    at null.emit (events.js:172:7)
[nodemon] app crashed - waiting for file changes before starting...
```
**Error in browser:**
```
ECONNRESET: Request could not be proxied!
There was an error proxying the request.
```
**Background:**

- node v4.6.1
- ubuntu 14.04.3 LTS
- cloud9

**Step to reproduce:**

1. Install MongoDB
```
sudo apt-get install -y mongodb-org
```
2. Install mern-cli
3. Create new app
4. Run Mongo in one terminal
```
mongod --bind_ip=$IP --nojournal
```
5. Run ```npm start``` in another terminal

**Comment by tpham045** [comment]
Try again. It works but hate why that happened.
