### ISSUE TITLE
Add a little something in the README about needing to install and boot up Mongo :D

### ISSUE THREAD

**Issue by beaucharman** [Hashnode/mern-starter#29]
```
.../mern-starter/node_modules/mongodb/lib/server.js:236
        process.nextTick(function() { throw err; })
Error: connect ECONNREFUSED
    at errnoException (net.js:904:11)
    at Object.afterConnect [as oncomplete] (net.js:895:19)
```

Obviously need to run `mongod` first. Could this be added in the `npm start`?

**Comment by mayankchd** [comment]
@beaucharman PR's,  welcomed!

**Comment by beaucharman** [comment]
Addressed in https://github.com/Hashnode/mern-starter/pull/35
