### ISSUE TITLE
can't run a Project if folder name has a space

### ISSUE THREAD

**Issue by Chathula** [Hashnode/mern-starter#291]
i tried to run a project with parent folder has a name with space. it failed!

```
Error: Cannot find module '/mnt/7A75BC6037968B45/00'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
/mnt/7A75BC6037968B45/00 Projects/00 Learning/mern-startup/node_modules/babel-core/lib/transformation/file/index.js:590
      throw err;
      ^
```

real folder name is `00 Projects`

**Comment by mannyhenri** [comment]
No you can't please change the name with underscore or other.
