### ISSUE TITLE
Mongo problem

### ISSUE THREAD

**Issue by TeodorKolev** [Hashnode/mern-starter#302]
Hello, I have pulled, install and run and I have this error:
```
C:\...\mern-starter-master\node_modules\mongodb\lib\server.js:267
        process.nextTick(function() { throw err; })
                                      ^
 MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECO
NNREFUSED 127.0.0.1:27017]
    at .<anonymous> (C:\...\mern-starter-master\node_modules\mongodb-core\lib\topol
ogies\server.js:327:35)
    at emitOne (events.js:96:13)
    at emit (events.js:188:7)
    at .<anonymous> (C:\U...\mern-starter-master\node_modules\mongodb-core\lib\conne
ction\pool.js:274:12)
    at g (events.js:286:16)
    at emitTwo (events.js:106:13)
    at emit (events.js:191:7)
    at Socket.<anonymous> (C:\...\mern-starter-master\node_modules\mongodb-core\lib
\connection\connection.js:177:49)
    at Socket.g (events.js:286:16)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1271:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```
Is there any possible solution for this. Do I miss something?

**Comment by peterpetre** [comment]
Hi, to start this repo you have to start mongodb on your machine too.
