### ISSUE TITLE
Mern-starter failed at cloud9 ide environment

### ISSUE THREAD

**Issue by kktam** [Hashnode/mern-starter#305]
when I try to use mern-cli in Cloud9. I ran into a problem with mern-starter during npm start.

The step `cross-env BABEL_DISABLE_CACHE=1 NODE_ENV=development nodemon index.js` caused an error. 

Any help to resolve this issue is most welcome.

```
~/workspace/myapp (master) $ npm start

> mern-starter@2.0.0 start /home/ubuntu/workspace/myapp
> cross-env BABEL_DISABLE_CACHE=1 NODE_ENV=development nodemon index.js

events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn nodemon ENOENT
    at exports._errnoException (util.js:907:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
    at Function.Module.runMain (module.js:443:11)
    at startup (node.js:139:18)
    at node.js:974:3

npm ERR! Linux 4.9.17-c9
npm ERR! argv "/home/ubuntu/.nvm/versions/node/v4.6.1/bin/node" "/home/ubuntu/.nvm/versions/node/v4.6.1/bin/npm" "start"
npm ERR! node v4.6.1
npm ERR! npm  v2.15.9
npm ERR! code ELIFECYCLE
npm ERR! mern-starter@2.0.0 start: `cross-env BABEL_DISABLE_CACHE=1 NODE_ENV=development nodemon index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mern-starter@2.0.0 start script 'cross-env BABEL_DISABLE_CACHE=1 NODE_ENV=development nodemon index.js'.
npm ERR! This is most likely a problem with the mern-starter package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env BABEL_DISABLE_CACHE=1 NODE_ENV=development nodemon index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mern-starter
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls mern-starter
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/workspace/myapp/npm-debug.log
```

**Comment by sw-yx** [comment]
same issue

**Comment by Vortelf** [comment]
The same issue happens with new mern-cli project.

**Comment by Aroniez** [comment]
+1

**Comment by mannyhenri** [comment]
Are there any specific requirements to the env variable with cloud9? Not familiar with them.

**Comment by MrChristofferson** [comment]
Spun up a c9 instance, followed the step-by-step for the cli in the readme, and couldn't reproduce.

Full output: 
```
ec2-user:~/environment $   npm install -g mern-cli
[..................] / normalizeTree: sill install loadCurrentTree
/home/ec2-user/.nvm/versions/node/v6.14.2/bin/mern -> /home/ec2-user/.nvm/versions/node/v6.14.2/lib/node_modules/mern-cli/bin/mern.js
/home/ec2-user/.nvm/versions/node/v6.14.2/bin/merng -> /home/ec2-user/.nvm/versions/node/v6.14.2/lib/node_modules/mern-cli/bin/merng.js
/home/ec2-user/.nvm/versions/node/v6.14.2/lib
└─┬ mern-cli@3.0.1 
  ├─┬ chalk@1.1.3 
  │ ├── ansi-styles@2.2.1 
  │ ├── escape-string-regexp@1.0.5 
  │ ├─┬ has-ansi@2.0.0 
  │ │ └── ansi-regex@2.1.1 
  │ ├── strip-ansi@3.0.1 
  │ └── supports-color@2.0.0 
  ├─┬ cli-table@0.3.1 
  │ └── colors@1.0.3 
  ├── commander@2.15.1 
  ├── ejs@2.6.1 
  ├── elegant-spinner@1.0.1 
  ├─┬ log-update@1.0.2 
  │ ├── ansi-escapes@1.4.0 
  │ └─┬ cli-cursor@1.0.2 
  │   └─┬ restore-cursor@1.0.1 
  │     ├── exit-hook@1.1.1 
  │     └── onetime@1.1.0 
  ├── shelljs@0.6.1 
  └─┬ writefile@0.2.8 
    ├─┬ lift-result@0.1.5 
    │ └─┬ result@1.0.3 
    │   └─┬ result-core@1.2.1 
    │     └── next-tick@0.0.2  (git://github.com/timoxley/next-tick.git#6f25f8c2d25697dead7e49e978ae4c31703f7490)
    ├─┬ mkdirp@0.5.1 
    │ └── minimist@0.0.8 
    └── result-type@1.0.0 

ec2-user:~/environment $ 
ec2-user:~/environment $   mern init your_new_app
Initialized empty Git repository in /home/ec2-user/environment/your_new_app/.git/
Fetching the boilerplate...⠇
From https://github.com/Hashnode/mern-starter
Completed.....You are good to go!
ec2-user:~/environment $   cd your_new_app
ec2-user:~/environment/your_new_app (master) $ 
ec2-user:~/environment/your_new_app (master) $   npm install
npm WARN deprecated babel-preset-es2015@6.24.1:   Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update! 
npm WARN deprecated postcss-cssnext@2.11.0: 'postcss-cssnext' has been deprecated in favor of 'postcss-preset-env'. Read more at https://moox.io/blog/deprecating-cssnext/
npm WARN deprecated formatio@1.1.1: This package is unmaintained. Use @sinonjs/formatio instead
npm WARN deprecated formidable@1.0.17: Old versions of Formidable are not compatible with the current Node.js; Upgrade to 1.2.0 or later

> nodejieba@2.2.6 install /home/ec2-user/environment/your_new_app/node_modules/nodejieba
> node-gyp rebuild



ec2-user:~/environment/your_new_app (master) $   npm start

> mern-starter@2.0.0 start /home/ec2-user/environment/your_new_app
> cross-env BABEL_DISABLE_CACHE=1 NODE_ENV=development nodemon index.js

[nodemon] 1.17.5
[nodemon] reading config ./nodemon.json
[nodemon] to restart at any time, enter `rs`
[nodemon] or send SIGHUP to 4037 to restart
[nodemon] ignoring: ./.git/**/* node_modules/**/node_modules
[nodemon] watching: /home/ec2-user/environment/your_new_app/server/**/* /home/ec2-user/environment/your_new_app/Intl/**/*
[nodemon] watching extensions: js,json
[nodemon] starting `node index.js`
[nodemon] forking
[nodemon] child pid: 4048
[nodemon] watching 14 files
Warning: Accessing PropTypes via the main React package is deprecated, and will be removed in  React v16.0. Use the latest available v15.* prop-types package from npm instead. For info on usage, compatibility, migration and more, see https://fb.me/prop-types-docs
Warning: Accessing createClass via the main React package is deprecated, and will be removed in React v16.0. Use a plain JavaScript class instead. If you're not yet ready to migrate, create-react-class v15.* is available on npm as a temporary, drop-in replacement. For more info see https://fb.me/react-create-class
(node:4048) DeprecationWarning: `open()` is deprecated in mongoose >= 4.11.0, use `openUri()` instead, or set the `useMongoClient` option if using `connect()` or `createConnection()`. See http://mongoosejs.com/docs/4.x/docs/connections.html#use-mongo-client

MERN is running on port: 8080! Build something amazing!
Please make sure Mongodb is installed and running!
```
