### ISSUE TITLE
Empty project won't start: several errors

### ISSUE THREAD

**Issue by InacioNeto** [Hashnode/mern-starter#309]
Created an empty project. I believe the setup was done correctly. This is what I get after _npm start_:

```
> mern-starter@2.0.0 start /var/www/MERN/mern-starter/grabber-app
> cross-env BABEL_DISABLE_CACHE=1 NODE_ENV=development nodemon index.js
[nodemon] 1.11.0
[nodemon] reading config /var/www/MERN/mern-starter/grabber-app/nodemon.json
[nodemon] to restart at any time, enter `rs`
[nodemon] ignoring: /var/www/MERN/mern-starter/grabber-app/.git/**/* .nyc_output .sass-cache bower_components coverage /var/www/MERN/mern-starter/grabber-app/node_modules/**/* /var/www/MERN/mern-starter/grabber-app/.git/**/* node_modules/**/node_modules
[nodemon] watching: /var/www/MERN/mern-starter/grabber-app/server/**/* /var/www/MERN/mern-starter/grabber-app/Intl/**/*
[nodemon] watching extensions: js,json
[nodemon] starting `node index.js`
[nodemon] child pid: 9801
[nodemon] watching 14 files
Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.
Warning: RouterContext: React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement.
MERN is running on port: 8000! Build something amazing!
webpack built ad89fca951cb9995ce13 in 5761ms
Warning: Failed prop type: The prop `posts` is marked as required in `PostListPage`, but its value is `undefined`.
    in PostListPage (created by Connect(PostListPage))
    in Connect(PostListPage) (created by RouterContext)
    in div (created by App)
    in div (created by App)
    in div (created by App)
    in App (created by Connect(App))
    in Connect(App) (created by RouterContext)
    in RouterContext
    in IntlProvider (created by IntlWrapper)
    in IntlWrapper (created by Connect(IntlWrapper))
    in Connect(IntlWrapper)
    in Provider
Warning: Failed prop type: The prop `posts` is marked as required in `PostList`, but its value is `undefined`.
    in PostList (created by PostListPage)
    in PostListPage (created by Connect(PostListPage))
    in Connect(PostListPage) (created by RouterContext)
    in div (created by App)
    in div (created by App)
    in div (created by App)
    in App (created by Connect(App))
    in Connect(App) (created by RouterContext)
    in RouterContext
    in IntlProvider (created by IntlWrapper)
    in IntlWrapper (created by Connect(IntlWrapper))
    in Connect(IntlWrapper)
    in Provider
events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: Can't set headers after they are sent.
    at ServerResponse.setHeader (_http_outgoing.js:371:11)
    at ServerResponse.header (/var/www/MERN/mern-starter/grabber-app/node_modules/express/lib/response.js:725:10)
    at ServerResponse.send (/var/www/MERN/mern-starter/grabber-app/node_modules/express/lib/response.js:170:12)
    at ServerResponse.json (/var/www/MERN/mern-starter/grabber-app/node_modules/express/lib/response.js:256:15)
    at /var/www/MERN/mern-starter/grabber-app/server/controllers/post.controller.js:17:9
    at /var/www/MERN/mern-starter/grabber-app/node_modules/mongoose/lib/query.js:2749:9
    at process._tickCallback (internal/process/next_tick.js:109:7)
[nodemon] app crashed - waiting for file changes before starting...
^C[nodemon] exiting

```

**Comment by DaanVermunt** [comment]
I had the same problem because my mongoDB server was not running with correctly. After making sure mongo was running properly it worked.

**Comment by sayayinR** [comment]
I have exactly the same issue, MongoDB seems to be running fine. Any suggestions?

**Comment by DaanVermunt** [comment]
@sayayinR Is mongo running on the correct port and with the correct permission settings?

**Comment by MincePie** [comment]
Is the problem that mongodb is running on a different port to local host? I don't know how to configure them to run together? I'm stuck because I can't use terminal commands to start mongodb separately from yarn start - I can't have control of the terminal after one of these commands runs. If I run yarn start - I get an error that says: 

> 
> MERN is running on port: 8000! Build something amazing!
> Please make sure Mongodb is installed and running!
> 
> /Users//bak/node_modules/mongodb/lib/server.js:267
>         process.nextTick(function() { throw err; })
>                                       ^
> MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]
> 

Does anyone know how to resolve this problem?

**Comment by DaanVermunt** [comment]
@MincePie Have you tried using npm instead of yarn. Also see the installation guide on https://docs.mongodb.com/v3.0/installation/ for installing mongoDB. Beacause it seems like either mongo is running with the wrong permissions or not even running at all

**Comment by marvinjude** [comment]
I am currently facing same issue, the empty boilerplate won't run with "npm
start" or "npm run start" while Mongo db is running on default port

**Comment by DaanVermunt** [comment]
@marvinjude the express server expects it to run on port 27017, so is that set as your default mongo port? And are you sure that the user starting the application is the same user as the user running mongo? And are you running >= npm3 which is indicated as required for the dependencies to work properly.
