### ISSUE TITLE
Installing on gentoo

### ISSUE THREAD

**Issue by vzx7** [Hashnode/mern-starter#311]
```
$ uname -a
Linux myserver 4.4.39-gentoo #2 SMP Sun Feb 5 08:37:50 +07 2017 x86_64 AMD A8-7600 Radeon R7, 10 Compute Cores 4C+6G AuthenticAMD GNU/Linux

$ node --version
v6.9.4

$ npm --version
3.10.10

$ mongo --version
MongoDB shell version: 3.0.14

$ DEBUG=* npm install

> mongodb-prebuilt@5.0.8 postinstall /home/vz_x/NODE/MERN/MernStart/node_modules/mongodb-prebuilt
> node install.js

done
  mongodb-prebuilt installing version: 3.2.10 +0ms
  mongodb-download selected platform linux +2ms
  mongodb-download selected architecture x86_64 +1ms
  mongodb-download selected version: 3.2.10 +0ms
  mongodb-download os dump { os: 'linux', dist: 'Ubuntu Linux' } +4ms
/home/vz_x/NODE/MERN/MernStart/node_modules/mongodb-download/index.js:86
				var ubuntu_version = os.release.split('.');
				                               ^

TypeError: Cannot read property 'split' of undefined
    at /home/vz_x/NODE/MERN/MernStart/node_modules/mongodb-download/index.js:86:36
    at /home/vz_x/NODE/MERN/MernStart/node_modules/getos/index.js:100:16
    at /home/vz_x/NODE/MERN/MernStart/node_modules/async/dist/async.js:356:16
    at iteratorCallback (/home/vz_x/NODE/MERN/MernStart/node_modules/async/dist/async.js:936:13)
    at /home/vz_x/NODE/MERN/MernStart/node_modules/async/dist/async.js:840:16
    at /home/vz_x/NODE/MERN/MernStart/node_modules/getos/index.js:95:18
    at /home/vz_x/NODE/MERN/MernStart/node_modules/async/dist/async.js:3025:16
    at eachOfArrayLike (/home/vz_x/NODE/MERN/MernStart/node_modules/async/dist/async.js:941:9)
    at eachOf (/home/vz_x/NODE/MERN/MernStart/node_modules/async/dist/async.js:991:5)
    at Object.eachLimit (/home/vz_x/NODE/MERN/MernStart/node_modules/async/dist/async.js:3089:3)
mern-starter@2.0.0 /home/vz_x/NODE/MERN/MernStart
└── UNMET PEER DEPENDENCY webpack@2.1.0-beta.8
```

**Comment by vzx7** [comment]
So what's next?..

**Comment by pak11273** [comment]
I think this project has been abandoned

**Comment by vzx7** [comment]
And I...

**Comment by mannyhenri** [comment]
thanks for reporting this, we're currently focusing on upgrading React, and will fix any bugs that prevent the initial project generated by the cli to work. Most errors in the meantime can be fixed by removing `^` to the dependencies, ex.: `"mockgoose": "^6.0.3"` to `"mockgoose": "6.0.3"` to lock in the version in the package.json file.
