### ISSUE TITLE
Error while doing npm install. 

### ISSUE THREAD

**Issue by adhikariraju** [Hashnode/mern-starter#319]
```
F:\Backup Folder\Projects\sdcsanjal\node_modules\nodejieba>if not defined npm_config_node_gyp (node "C:\Users\crony\AppData\Roaming\npm\node_mo
dules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at Object.failNoPython (C:\Users\crony\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at Object.<anonymous> (C:\Users\crony\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at C:\Users\crony\AppData\Roaming\npm\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:123:15)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\crony\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin
\\node-gyp.js" "rebuild"
gyp ERR! cwd F:\Backup Folder\Projects\sdcsanjal\node_modules\nodejieba
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok

```

Even if i install python and set environment variable same error is shown

**Comment by flickz** [comment]
Node module 'node-gyp.js' requires python to work. Install python and add to path. Now try npm install.

**Comment by flickz** [comment]
What python version do you have installed? 
"Can't find Python executable "python", you can set the PYTHON env variable" - Try to reinstall  python and add to path again.
