### ISSUE TITLE
running merng produces an error 

### ISSUE THREAD

**Issue by sanketsingh24** [Hashnode/mern-starter#376]
When i run merng, it produces the following error-

```
user@mypc:~/Documents/node_modules/mern-cli/urapp$ node ../bin/merng.js

  Usage: merng [options] <generator> [args]

  Generate components, routes, controllers, models using mern generator

  Options:

    -h, --help  output usage information
Available Generators
____________________

/home/user/Documents/node_modules/mern-cli/lib/commands/generate.js:43
    blueprints.forEach(function (b) {
               ^

TypeError: Cannot read property 'forEach' of undefined
    at Command.<anonymous> (/home/user/Documents/node_modules/mern-cli/lib/commands/generate.js:43:16)
    at emitNone (events.js:106:13)
    at Command.emit (events.js:208:7)
    at Command.outputHelp (/home/user/Documents/node_modules/commander/index.js:1146:8)
    at Command.help (/home/user/Documents/node_modules/commander/index.js:1156:8)
    at Object.<anonymous> (/home/user/Documents/node_modules/mern-cli/lib/commands/generate.js:49:25)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
```

I am running merng locally here, is that why this error is occuring?

wrt [this response](https://github.com/Hashnode/mern-cli/issues/33#issuecomment-396625857)

**Comment by mannyhenri** [comment]
Thanks for posting this. Let me test and provide feedback/fix.

**Comment by jr-smith** [comment]
still not able to run merng. Is there a time line when this will be done? Thanks!

**Comment by HansUXdev** [comment]
Same and this is really annoying because without a functioning cli its just a fullstack CRA... I came here seeing if there was a solution for why i cant generate anything...

**Comment by sanketsingh24** [comment]
Actually @mannyhenri asked me to reopen this here, I opened it on mern-cli originally.
