### ISSUE TITLE
Test GET /api/getPosts does not seem to be using provided data

### ISSUE THREAD

**Issue by joshmatz** [Hashnode/mern-starter#46]
**Issue:**
Knowing that the test `GET /api/getPosts` is hard coded to add exactly two posts to the database, I figured I'd try to speed up the test (mocha is often warning me these are taking >300ms) by hard coding the expectation:

```
  it('Should correctly give number of Posts', function (done) {
    request(app)
      .get('/api/getPosts')
      .set('Accept', 'application/json')
      .end(function (err, res) {
        expect(res.body.posts.length).to.equal(2);
        done();
      });
  });
```

Unfortunately, in doing so I noticed that the test _inconsistently_ fails with the change. I logged `res.body.posts` and it seems to be using the `mern-starter` database data:

```
res.body.posts:  [ { _id: '56c899d05eff2e3e9c205060',
    content: 'Sed ut perspiciatis unde omnis iste natus error\n      sit voluptatem accusantium doloremque laudantium, totam rem aperiam,\n      eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae\n      vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit\n      aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos\n      qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem\n      ipsum quia dolor sit amet. Lorem ipsum dolor sit amet, consectetur adipiscing elit,\n      sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut\n      enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi\n      ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit\n      in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint\n      occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id\n      est laborum',
    cuid: 'cikqgkv4q01ck7453ualdn3hd',
    slug: 'hello-mern',
    title: 'Hello MERN',
    name: 'Admin',
    __v: 0,
    dateAdded: '2016-02-20T16:52:32.105Z' } ]
```

With that knowledge, I'm not sure why:

1. the data is not the expected data set
1. this data randomly comes back with only one post?

**Test runs:**

```
 joshmatz@matzpro  ~/Projects/mynewapp   master ● 
» npm run test:server -s


MERN is running on port: 8080! Build something amazing!
  GET /api/getPosts
    ✓ Should correctly give number of Posts (691ms)

  GET /api/getPost
    ✓ Should send correct data when queried against a title (181ms)

  POST /api/addPost
webpack built b33d025a8833ae819e84 in 2593ms
    ✓ Should send correctly add a post (736ms)

  POST /api/deletePost
    ✓ Should connect and delete a post


  4 passing (3s)

 joshmatz@matzpro  ~/Projects/mynewapp   master ● 
» npm run test:server -s


MERN is running on port: 8080! Build something amazing!
  GET /api/getPosts
    1) Should correctly give number of Posts

  GET /api/getPost
    ✓ Should send correct data when queried against a title (204ms)

  POST /api/addPost
webpack built b33d025a8833ae819e84 in 2669ms
    ✓ Should send correctly add a post (493ms)

  POST /api/deletePost
    ✓ Should connect and delete a post


  3 passing (3s)
  1 failing

  1) GET /api/getPosts Should correctly give number of Posts:

      Uncaught AssertionError: expected 1 to equal 2
      + expected - actual

      -1
      +2

      at Test.<anonymous> (post.spec.js:58:42)
      at Test.assert (node_modules/supertest/lib/test.js:156:6)
      at Server.assert (node_modules/supertest/lib/test.js:127:12)
      at emitCloseNT (net.js:1521:8)
```

**Environment:**
mongo: 3.2.3
node: 4.2.2
OSX: 10.11.3

**Comment by stephan281094** [comment]
This issue can be closed. See #47.

**Comment by prank7** [comment]
Thanks @stephan281094. I will close it.
